### ISSUE TITLE
Add links to the docs in OCDS schema validation messages

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/cove-ocds#103]
From https://github.com/OpenDataServices/cove/issues/951#issuecomment-363448807. There was some work on this, but it was removed because changes to the docs site weren't merged yet. They now have been, so we can do this. Steps:

- [ ] Revert removal of docs urls https://github.com/OpenDataServices/cove/commit/8336e0f774463724480331edc72ee29e68ec09d1
- [ ] Update urls to point to the live standard docs
- [ ] Check that all the messages make sense for data with extensions

**Comment by jpmckinney** [comment]
`docs_ref` is set in `libcoveocds.common_checks` but is not used in cove-ocds.

**Comment by jpmckinney** [comment]
In the 2021 UX review (#223), the [audit results](https://docs.google.com/spreadsheets/d/1Hu3_QNXG9KK_8lBrVgcleBMy89CHCRohGbb--Xe1U64/edit?gid=0#gid=0) has "Each specific error type should refer to the relevant part of the documentation". The [DRT issue types](https://docs.google.com/spreadsheets/d/1S4qqY_l8Pyuw2rklSffaHIrtxhgiz7MJ9CyQY9btTrw/edit?gid=0#gid=0) spreadsheet has a "Documentation link" column, with the URL for the aprt of the documentation that is relevant to each specific error type. These URLs are mostly URLs like:

* https://standard.open-contracting.org/latest/en/schema/release/#release-schema
* https://standard.open-contracting.org/latest/en/schema/identifiers/#contracting-process-identifier-ocid
* etc.

The [requirements document](https://docs.google.com/document/d/1PnSlQfmKBjngISh20xjDjlNLwiIkyxIh9Cjn8EVUzEU/edit?tab=t.0) has (emphasis added) "As a user I would like to see a link to the relevant documentation **only if it exists to help me fix a specific error**, so I can quickly look up the information that I need to fix the issue with my data."

That emphasis is important. Linking to the individual field (like in this issue) is uninformative – it just restates the field name, title, and description, which are already in the DRT results, and it shows the type (which is also already in the DRT results, if the error is with respect to the type).

So, instead of providing links to individual fields, we'll implement the advice from the UX review, which is to add a link related to the error type (**not** the field) only if there is relevant documentation.
