### ISSUE TITLE
Validation error messages aren't translated

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/cove-ocds#104]

**Comment by jpmckinney** [comment]
Seems to be translated by lib-cove-web. Test data:

`{"version":"1.1","releases":[{"tender":{"title":1,"value":{"amount":"1"}}}]}`

https://github.com/OpenDataServices/lib-cove/blob/main/libcove/lib/common.py#L110-L118

https://github.com/OpenDataServices/lib-cove-web/blob/1a6c7ae3c0d93d8a7d6c98b58b4f85b9499ad2c3/cove/html_error_msg.py#L21-L31

FWIW lib-cove-ocds no longer needs Django in non-CoVE contexts since 0.12.0.

The ideas around refactoring belong as a lib-cove issue.
